import unittest
from fooddata import typeOfLine, singlelineToDict, seriousRowDecoder , violationsToList  , additonalViolations , makeChart, inspectionResults, restaurantsTypes
#from testFile import testFunction
#to test simply run 'python boilerplatetester.py'

class fooddataTestCase(unittest.TestCase):
    
    def test_single_good_line(self): #
        """ should succeed and demonstrates that typeOfLine can find a good single line log entry """
        expectedResult = 'singleline'
        testCase = '99888,ROOK CAFE AND SMOOTHIE BAR,ROOK CAFE AND SMOOTHIE BAR,2188890,'
        testCase += 'Restaurant,Risk 2 (Medium),816 S MICHIGAN AVE ,CHICAGO,IL,60605,03/06/2013,Complaint,Fail,'
        testCase += '"1. SOURCE SOUND CONDITION, NO SPOILAGE, FOODS PROPERLY LABELED, SHELLFISH TAGS IN PLACE - '
        testCase += 'Comments: UNAPPROVED SOURCE:FOUND 10 BUTTER COOKIES ON COUNTER FOR SALE WITHOUT PROPER LABELING AND NO INVOICE TO SHOW COOKIES COME FROM AN APPROVED SOURCE. INSTRUCTED TO PROVIDE/HAVE ON PREMISES AT ALL TIMES. CRITICAL VIOLATION 7-38-005(B) | 3. POTENTIALLY HAZARDOUS FOOD MEETS TEMPERATURE REQUIREMENT DURING STORAGE, PREPARATION DISPLAY AND SERVICE - Comments: FOUND A CONTAINER OF ITALIAN BEEF AT AN IMPROPER TEMPERATURE-55.3F, STORED IN THE REACH IN COOLER. ITEM WAS DISCARDED, 2LBS. VALUED AT $20.OO. INSTRUCTED TO KEEP POTENTIALLY HAZARDOUS FOODS AT 40F OR LOWER. CRITICAL VIOLATION 7-38-005(A) | 9. WATER SOURCE: SAFE, HOT & COLD UNDER CITY PRESSURE - Comments: FOUND NO HOT WATER PER CITY CODE ON THE PREMISES. INSTRUCTED TO HAVE HOT WATER ON THE PREMISES AT ALL TIMES. CRITICAL VIOLATION 7-38-030 | 35. WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTRUCTED PER CODE: GOOD REPAIR, SURFACES CLEAN AND DUST-LESS CLEANING METHODS - Comments: MUST REPLACE WATER STAINED CEILING IN DINING AREA. | 41. PREMISES MAINTAINED FREE OF LITTER, UNNECESSARY ARTICLES, CLEANING  EQUIPMENT PROPERLY STORED - Comments: MUST ELIMINATE ALL UNNECESSARY ARTICLES IN PREP AREA AND ORGANIZE AREA. | 32. FOOD AND NON-FOOD CONTACT SURFACES PROPERLY DESIGNED, CONSTRUCTED AND MAINTAINED - Comments: MUST PROVIDE A SNEEZE GUARD OVER HOT HOLDING FOOD ITEMS ON THE FRONT COUNTER. | 38. VENTILATION: ROOMS AND EQUIPMENT VENTED AS REQUIRED: PLUMBING: INSTALLED AND MAINTAINED - Comments: MUST FIX SLOW DRAINING 3-COMP. SINK IN PREP AREA.",41.87162384657216,-87.62431054852696,"(41.87162384657216, -87.62431054852696)"'
        self.assertTrue(typeOfLine(testCase) == expectedResult)
    
    def test_single_bad_line(self):
        """ should not succeed and demonstrates that typeOfLine will not pass everything close to a single line entry"""
        expectedResult = 'singleline'
        testCase = 'VODKA IS YUMMY,ROOK CAFE AND SMOOTHIE BAR,a;lsdka;lskdjflkajsdfoiajwe;ncajwehi;ef"1. SOURCE SOUND CONDITION, NO SPOILAGE, FOODS PROPERLY LABELED, SHELLFISH TAGS IN PLACE - Comments: UNAPPROVED SOURCE:FOUND 10 BUTTER COOKIES ON COUNTER FOR SALE WITHOUT PROPER LABELING AND NO INVOICE TO SHOW COOKIES COME FROM AN APPROVED SOURCE. INSTRUCTED TO PROVIDE/HAVE ON PREMISES AT ALL TIMES. CRITICAL VIOLATION 7-38-005(B) | 3. POTENTIALLY HAZARDOUS FOOD MEETS TEMPERATURE REQUIREMENT DURING STORAGE, PREPARATION DISPLAY AND SERVICE - Comments: FOUND A CONTAINER OF ITALIAN BEEF AT AN IMPROPER TEMPERATURE-55.3F, STORED IN THE REACH IN COOLER. ITEM WAS DISCARDED, 2LBS. VALUED AT $20.OO. INSTRUCTED TO KEEP POTENTIALLY HAZARDOUS FOODS AT 40F OR LOWER. CRITICAL VIOLATION 7-38-005(A) | 9. WATER SOURCE: SAFE, HOT & COLD UNDER CITY PRESSURE - Comments: FOUND NO HOT WATER PER CITY CODE ON THE PREMISES. INSTRUCTED TO HAVE HOT WATER ON THE PREMISES AT ALL TIMES. CRITICAL VIOLATION 7-38-030 | 35. WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTRUCTED PER CODE: GOOD REPAIR, SURFACES CLEAN AND DUST-LESS CLEANING METHODS - Comments: MUST REPLACE WATER STAINED CEILING IN DINING AREA. | 41. PREMISES MAINTAINED FREE OF LITTER, UNNECESSARY ARTICLES, CLEANING  EQUIPMENT PROPERLY STORED - Comments: MUST ELIMINATE ALL UNNECESSARY ARTICLES IN PREP AREA AND ORGANIZE AREA. | 32. FOOD AND NON-FOOD CONTACT SURFACES PROPERLY DESIGNED, CONSTRUCTED AND MAINTAINED - Comments: MUST PROVIDE A SNEEZE GUARD OVER HOT HOLDING FOOD ITEMS ON THE FRONT COUNTER. | 38. VENTILATION: ROOMS AND EQUIPMENT VENTED AS REQUIRED: PLUMBING: INSTALLED AND MAINTAINED - Comments: MUST FIX SLOW DRAINING 3-COMP. SINK IN PREP AREA.",41.87162384657216,-87.62431054852696,"(41.87162384657216, -87.62431054852696)"'
        self.assertTrue(typeOfLine(testCase) != expectedResult)
    
    def test_blank_good_line(self): #
        """ should succeed and demonstrates that typeOfLine can find and id a blank line log entry """
        expectedResult = 'blank'
        testCase = ' '
        self.assertTrue(typeOfLine(testCase) == expectedResult)
    
    def test_blank_bad_line(self): #
        """ should fail and demonstrates that typeOfLine can find and id a blank line log entry """
        expectedResult = 'blank'
        testCase = ' . '
        self.assertTrue(typeOfLine(testCase) != expectedResult)
    
    def test_cont_good_line(self): #
        """ should fail and demonstrates that typeOfLine can find and id a blank line log entry """
        expectedResult = 'cont'
        testCase = ' | 35. WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTRUCTED PER CODE: GOOD REPAIR, SURFACES CLEAN AND DUST-LESS CLEANING METHODS - Comments: WALLS AROUND 3 COMPARTMENT SINK IN NEED OF CLEANING TO REMOVE SPLATTER. '
        self.assertTrue(typeOfLine(testCase) == expectedResult)
    
    def test_serious_good1_line(self): #
        """ should succeed and demonstrates that typeOfLine can find and id a serious (critical) violation (citation) line log entry 1st case """
        expectedResult = 'serious'
        testCase = 'SERIOUS VIOLATION 7-38-012 CITATION ISSUED'
        self.assertTrue(typeOfLine(testCase) == expectedResult)
    
    def test_serious_good2_line(self): #
        """ should succeed and demonstrates that typeOfLine can find and id a serious (critical) violation (citation) line log entry 2nd case"""
        expectedResult = 'serious'
        testCase = 'CRITICAL CITATION ISSUED: 7-38-005 (A) \| 3. POTENTIALLY HAZARDOUS FOOD MEETS TEMPERATURE REQUIREMENT DURING STORAGE, PREPARATION DISPLAY AND SERVICE - Comments: OBSERVED PREPARED COOKED FOODS IN DISPLAY COOLER CASE READING AT IMPROPER TEMP., READING BETWEEN 48.7-50.1\'F, ALL PRODUCT DUMPED AND DENATURE AT A COST OF ABOUT $676.00, AND ABOUT 181.60 POUNDS, INSTRUCTED MANAGER THAT PIZZA THATS READING 29\'F, CAN BE SOLD, BUT NOT REFROZEN, MANAGER DECIDED TO DISCARD PIZZA, AT A COST OF ABOUT $889.20, AND ABOUT 275 POUNDS, SEE ATTACHED INVOICES AND RECEIPTS, '
        self.assertTrue(typeOfLine(testCase) == expectedResult)
        
    def test_serious_good3_line(self): #
        """ should succeed and demonstrates that typeOfLine can find and id a serious (critical) violation (citation) line log entry 3rd case"""
        expectedResult = 'serious'
        testCase = 'SERIOUS CITATION ISSUED: 7-38-020 | 33. FOOD AND NON-FOOD CONTACT EQUIPMENT UTENSILS CLEAN, FREE OF ABRASIVE DETERGENTS - Comments: MUST DETAIL CLEAN: TOPS AND SIDE OF COOKING EQUIPMENT, VENTS ABOVE COOKING EQUIPMENT, VENTS ABOVE DISH MACHINES NOT CLEAN, AND EXTERIOR SURFACES OF BULK CONTAINERS, AT BOTH PREP AREAS, 1ST AND 2ND FLOORS, MUST DETAIL CLEAN ALL SURFACES | 32. FOOD AND NON-FOOD CONTACT SURFACES PROPERLY DESIGNED, CONSTRUCTED AND MAINTAINED - Comments: MUST PROVIDE SPLASH GUARDS AT EXPOSED HAND SINKS AT BAR AREAS, BETWEEN COUNTER AREA AND THREE COMPARTMENT SINKS | 34. FLOORS: CONSTRUCTED PER CODE, CLEANED, GOOD REPAIR, COVERING INSTALLED, DUST-LESS CLEANING METHODS USED - Comments: FLOORS THROUGHOUT PREMISES, UNDER AND BEHIND ALL EQUIPMENT, ON ALL FLOORS NEEDS DETAILED CLEANING, AND RESTRICT STORING ARTICLES ON FLOOR, MUST BE 6 INCHES FROM FLOOR AND WALL | 35. WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTRUCTED PER CODE: GOOD REPAIR, SURFACES CLEAN AND DUST-LESS CLEANING METHODS - Comments: WALL SECOND FLOOR STORAGE AREA NEEDS SEALED, TO REMOVE ALL DUSTY BRICK PARTICLES FROM COMING OFF OF WALL, SURFACES MUST BE SMOOTH AND EASILY CLEANABLE | 36. LIGHTING: REQUIRED MINIMUM FOOT-CANDLES OF LIGHT PROVIDED, FIXTURES SHIELDED - Comments: MUST INCREASE LIGHT IN FIRST FLOOR KITCHEN PREP AND DISH AREA, LIGHT TOO DIM | 37. TOILET ROOM DOORS SELF CLOSING: DRESSING ROOMS WITH LOCKERS PROVIDED: COMPLETE SEPARATION FROM LIVING/SLEEPING QUARTERS - Comments: PERSONAL ITEMS STORED IN BASEMENT, NOT STORED NEATLY, MUST BE ONE DESIGNATED AREA, NICE AND NEATLY | 41. PREMISES MAINTAINED FREE OF LITTER, UNNECESSARY ARTICLES, CLEANING  EQUIPMENT PROPERLY STORED - Comments: MUST CLEAN AND BETTER ORGANIZE, ALL STORAGE AREAS, REMOVE ALL CLUTTER, CLEAN AND BETTER MAINTAIN ALL AREAS, MUST ELEVATE ALL ARTICLES 6 INCHES FROM FLOOR AND WALL, AND PROVIDE SHELVING TO BETTER MAINTAIN",41.92353245816767,-87.69813956418868,"(41.92353245816767, -87.69813956418868)"'
        self.assertTrue(typeOfLine(testCase) == expectedResult)    
       
    def test_serious_bad_line(self): #
        """ should fail and demonstrates that typeOfLine can find and id a blank line log entry """
        expectedResult = 'serious'
        testCase = 'LABEL ALL FOODS WITH NAME AND DATE.",41.96846837763899,-87.69299972102974,"(41.96846837763899, -87.69299972102974)"'
        self.assertTrue(typeOfLine(testCase) != expectedResult)
    
    def test_singlerowToDict(self):
        """takes a row already IDed to be a single row and returns a dict with matching lables and data for that row.
        then each Item is tested"""
        testCase = r'585972,MR.TACO,MR.TACO,2099526,Restaurant,Risk 1 (High),3330-3332 N BROADWAY ,CHICAGO,IL,60657,07/25/2011,License Re-Inspection,Pass,"18. NO EVIDENCE OF RODENT OR INSECT OUTER OPENINGS PROTECTED/RODENT PROOFED, A WRITTEN LOG SHALL BE MAINTAINED AVAILABLE TO THE INSPECTORS - Comments:  | 32. FOOD AND NON-FOOD CONTACT SURFACES PROPERLY DESIGNED, CONSTRUCTED AND MAINTAINED - Comments:  | 34. FLOORS: CONSTRUCTED PER CODE, CLEANED, GOOD REPAIR, COVERING INSTALLED, DUST-LESS CLEANING METHODS USED - Comments:  | 35. WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTRUCTED PER CODE: GOOD REPAIR, SURFACES CLEAN AND DUST-LESS CLEANING METHODS - Comments:  | 36. LIGHTING: REQUIRED MINIMUM FOOT-CANDLES OF LIGHT PROVIDED, FIXTURES SHIELDED - Comments:  | 40. REFRIGERATION AND METAL STEM THERMOMETERS PROVIDED AND CONSPICUOUS - Comments: ",41.942717387425816,-87.64463491821648,"(41.942717387425816, -87.64463491821648)"'
        results  =  singlelineToDict(testCase)
        self.assertEqual(results ['InspectionID'], '585972' )
        self.assertEqual(results ['DBAName'], 'MR.TACO' )
        self.assertEqual(results ['AKAName'], 'MR.TACO' )
        self.assertEqual(results ['License'], '2099526' )
        self.assertEqual(results ['FacilityType'], 'Restaurant'.upper() )
        self.assertEqual(results ['Risk'], r'Risk 1 (High)'.upper() )
        self.assertEqual(results ['Address'], '3330-3332 N BROADWAY ' )
        self.assertEqual(results ['City'], 'CHICAGO' )
        self.assertEqual(results ['State'], 'IL' )
        self.assertEqual(results ['Zip'], '60657' )
        self.assertEqual(results ['InspectionDate'], r'07/25/2011' )
        self.assertEqual(results ['InspectionType'], 'License Re-Inspection'.upper() )
        self.assertEqual(results ['Results'], 'Pass'.upper() )
        self.assertEqual(results ['Violations'], violationsToList(r'"18. NO EVIDENCE OF RODENT OR INSECT OUTER OPENINGS PROTECTED/RODENT PROOFED, A WRITTEN LOG SHALL BE MAINTAINED AVAILABLE TO THE INSPECTORS - Comments:  | 32. FOOD AND NON-FOOD CONTACT SURFACES PROPERLY DESIGNED, CONSTRUCTED AND MAINTAINED - Comments:  | 34. FLOORS: CONSTRUCTED PER CODE, CLEANED, GOOD REPAIR, COVERING INSTALLED, DUST-LESS CLEANING METHODS USED - Comments:  | 35. WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTRUCTED PER CODE: GOOD REPAIR, SURFACES CLEAN AND DUST-LESS CLEANING METHODS - Comments:  | 36. LIGHTING: REQUIRED MINIMUM FOOT-CANDLES OF LIGHT PROVIDED, FIXTURES SHIELDED - Comments:  | 40. REFRIGERATION AND METAL STEM THERMOMETERS PROVIDED AND CONSPICUOUS - Comments: "' ))
        self.assertEqual(results ['Latitude'], '41.942717387425816' )
        self.assertEqual(results ['Longitude'], '-87.64463491821648' )
        self.assertEqual(results ['Location'], r'"(41.942717387425816, -87.64463491821648)"' )
     
    def test_additionalViolations(self):
        """
        takes a single line loads it into a dictionary, 
        then takes a line of violations and loads them as well 
        it lists the items in violations and assets that they are correct.
        """
        self.maxDiff = None
        testCase = r'585972,MR.TACO,MR.TACO,2099526,Restaurant,Risk 1 (High),3330-3332 N BROADWAY ,CHICAGO,IL,60657,07/25/2011,License Re-Inspection,Pass,"18. NO EVIDENCE OF RODENT OR INSECT OUTER OPENINGS PROTECTED/RODENT PROOFED, A WRITTEN LOG SHALL BE MAINTAINED AVAILABLE TO THE INSPECTORS - Comments:  | 32. FOOD AND NON-FOOD CONTACT SURFACES PROPERLY DESIGNED, CONSTRUCTED AND MAINTAINED - Comments:  | 34. FLOORS: CONSTRUCTED PER CODE, CLEANED, GOOD REPAIR, COVERING INSTALLED, DUST-LESS CLEANING METHODS USED - Comments:  | 35. WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTRUCTED PER CODE: GOOD REPAIR, SURFACES CLEAN AND DUST-LESS CLEANING METHODS - Comments:  | 36. LIGHTING: REQUIRED MINIMUM FOOT-CANDLES OF LIGHT PROVIDED, FIXTURES SHIELDED - Comments:  | 40. REFRIGERATION AND METAL STEM THERMOMETERS PROVIDED AND CONSPICUOUS - Comments: ",41.942717387425816,-87.64463491821648,"(41.942717387425816, -87.64463491821648)"'
        testCaseCont = r'\| 40. REFRIGERATION AND METAL STEM THERMOMETERS PROVIDED AND CONSPICUOUS - Comments: VIOLATION CORRECTED. | 41. PREMISES MAINTAINED FREE OF LITTER, UNNECESSARY ARTICLES, CLEANING  EQUIPMENT PROPERLY STORED - Comments: DETAIL CLEAN AND ORGANIZE KITCHEN FOOD PREP AREAS,2ND FLOOR DRY STORAGE ROOMS,LAUNDRY ROOM AND REMOVE UNNECESSARY ARTICLES THROUGHOUT DUE TO POTENTIAL PEST HARBORAGE.ALL ITEMS KEPT MUST BE NEAT,SANITARY 6'+"'"+' OFF FLOOR/WALL.REMOVE CLUTTERED CONDITIONS FROM THE 3RD FLOOR STORAGE AND FROM INSIDE THE TOOL ROOM SAME AREA. | 16. FOOD PROTECTED DURING STORAGE, PREPARATION, DISPLAY, SERVICE AND TRANSPORTATION - Comments: VIOLATION CORRECTED."'
        resultInitial  =  singlelineToDict(testCase)
        #resultInitial['Violations']  =  violationsToList(resultInitial['Violations'])
        expectedResult = resultInitial['Violations'] + [r'40. REFRIGERATION AND METAL STEM THERMOMETERS PROVIDED AND CONSPICUOUS - Comments: VIOLATION CORRECTED. | ', r'41. PREMISES MAINTAINED FREE OF LITTER, UNNECESSARY ARTICLES, CLEANING  EQUIPMENT PROPERLY STORED - Comments: DETAIL CLEAN AND ORGANIZE KITCHEN FOOD PREP AREAS,2ND FLOOR DRY STORAGE ROOMS,LAUNDRY ROOM AND REMOVE UNNECESSARY ARTICLES THROUGHOUT DUE TO POTENTIAL PEST HARBORAGE.ALL ITEMS KEPT MUST BE NEAT,SANITARY 6'+"'"+' OFF FLOOR/WALL.REMOVE CLUTTERED CONDITIONS FROM THE 3RD FLOOR STORAGE AND FROM INSIDE THE TOOL ROOM SAME AREA. | ', r'16. FOOD PROTECTED DURING STORAGE, PREPARATION, DISPLAY, SERVICE AND TRANSPORTATION - Comments: VIOLATION CORRECTED."']
        actualResult = additonalViolations(resultInitial, testCaseCont)
        self.assertEqual(expectedResult , actualResult['Violations'] )
     
    def test_serious_Row1(self):
        testCase = r'SERIOUS CITATION ISSUED: 7-42-090'
        results = seriousRowDecoder(testCase)
        self.assertEqual(results['label'], 'SERIOUS CITATION' )
        self.assertEqual(results['number'], '7-42-090' )
        
    def test_serious_Row2(self):    
        testCase = r'CRITICAL VIOLATION 7-42-090 CITATION ISSUED.'
        results = seriousRowDecoder(testCase)
        self.assertEqual(results['label'], 'CRITICAL CITATION' )
        self.assertEqual(results['number'], '7-42-090' )
    
    def test_serious_Row3(self):
        testCase = r'SERIOUS VIOLATION: 7-42-090'
        results = seriousRowDecoder(testCase)
        self.assertEqual(results['label'], 'SERIOUS VIOLATION' )
        self.assertEqual(results['number'], '7-42-090' )
        
    # def test_violations(self):
        # self.maxDiff = None
        # testCase = r'"18. NO EVIDENCE OF RODENT OR INSECT OUTER OPENINGS PROTECTED/RODENT PROOFED, A WRITTEN LOG SHALL BE MAINTAINED AVAILABLE TO THE INSPECTORS - Comments:  | 32. FOOD AND NON-FOOD CONTACT SURFACES PROPERLY DESIGNED, CONSTRUCTED AND MAINTAINED - Comments:  | 34. FLOORS: CONSTRUCTED PER CODE, CLEANED, GOOD REPAIR, COVERING INSTALLED, DUST-LESS CLEANING METHODS USED - Comments:  | 35. WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTRUCTED PER CODE: GOOD REPAIR, SURFACES CLEAN AND DUST-LESS CLEANING METHODS - Comments:  | 36. LIGHTING: REQUIRED MINIMUM FOOT-CANDLES OF LIGHT PROVIDED, FIXTURES SHIELDED - Comments:  | 40. REFRIGERATION AND METAL STEM THERMOMETERS PROVIDED AND CONSPICUOUS - Comments: "'
        # results = violationsToList(testCase)
        # expectedResult =  [r'18. NO EVIDENCE OF RODENT OR INSECT OUTER OPENINGS PROTECTED/RODENT PROOFED, A WRITTEN LOG SHALL BE MAINTAINED AVAILABLE TO THE INSPECTORS - Comments:  | ', r'32. FOOD AND NON-FOOD CONTACT SURFACES PROPERLY DESIGNED, CONSTRUCTED AND MAINTAINED - Comments:  | ', r'34. FLOORS: CONSTRUCTED PER CODE, CLEANED, GOOD REPAIR, COVERING INSTALLED, DUST-LESS CLEANING METHODS USED - Comments:  | ', r'35. WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTRUCTED PER CODE: GOOD REPAIR, SURFACES CLEAN AND DUST-LESS CLEANING METHODS - Comments:  | ', r'36. LIGHTING: REQUIRED MINIMUM FOOT-CANDLES OF LIGHT PROVIDED, FIXTURES SHIELDED - Comments:  | ', r'40. REFRIGERATION AND METAL STEM THERMOMETERS PROVIDED AND CONSPICUOUS - Comments: "']
        # self.assertEqual(results, expectedResult )
    def test_makeChart(self):
        testCase = dict()
        testCase["control chart title"] = 'chartable.htm'
        testCase["control chart options"] = """
        var options = {
          title: 'testchar',
          is3D: true,
        };
        """
        testCase['six'] = 6
        testCase['one'] = 1
        testCase['three'] = 3 
        self.assertTrue(not makeChart(testCase) )
    def test_inspectionResults(self):
        testCase = dict()
        testCase["control chart title"] = 'inspectionResultsTest.htm'
        testCase["control chart options"] = """
        var options = {
          title: 'Inspection Results',
          is3D: true,
        };
        """
        inspection = singlelineToDict('1326219,EUREST DINING,CAFE 330,2233306,Restaurant,Risk 1 (High),330 N WABASH AVE ,CHICAGO,IL,60611,03/08/2013,License Re-Inspection,Pass,,,,')
        testCase[inspection['InspectionID'] ] = inspection
        inspection = singlelineToDict('1326216,INSOMNIA COOKIES,,2231962,,,2260 N LINCOLN AVE ,CHICAGO,IL,60614,03/08/2013,License,Fail,,41.92316234375516,-87.64578239312512,"(41.92316234375516, -87.64578239312512)"')
        testCase[inspection['InspectionID'] ] = inspection
        inspection = singlelineToDict('1326213,GALE STREET INN,GALE STREET INN,39301,Restaurant,Risk 1 (High),4914 N MILWAUKEE AVE ,CHICAGO,IL,60630,03/08/2013,Complaint,Pass,"40. REFRIGERATION AND METAL STEM THERMOMETERS PROVIDED AND CONSPICUOUS - Comments: INSTRUCTED TO PROVIDE THERMOMETER VISIBLE INSIDE (2) WALK-IN COOLER. | 41. PREMISES MAINTAINED FREE OF LITTER, UNNECESSARY ARTICLES, CLEANING  EQUIPMENT PROPERLY STORED - Comments: INSTRUCTED TO REMOVE UNNECESSARY ARTICLES STORED ON TOP OF WALK-IN COOLER AND WALK-IN FREEZER TO PREVENT PEST HARBORAGE. | 38. VENTILATION: ROOMS AND EQUIPMENT VENTED AS REQUIRED: PLUMBING: INSTALLED AND MAINTAINED - Comments: INSTRUCTED TO FIX LEAKY (COLD) FAUCET HANDLE LEAK AT EXPOSED HANDSINK IN MAIN PREP AREA (COOKING LINE).",41.97001167825235,-87.76279618588528,"(41.97001167825235, -87.76279618588528)"')
        testCase[inspection['InspectionID'] ] = inspection
        inspection = singlelineToDict('1326212,WILLIAM\'S PRODUCE,WILLIAM\'S PRODUCE,2079521,GROCERY STORE/TAQUERIA,Risk 1 (High),6309 W GRAND AVE ,CHICAGO,IL,60639,03/08/2013,Canvass,Out of Business,,41.92189422993173,-87.78339752005009,"(41.92189422993173, -87.78339752005009)"')
        testCase[inspection['InspectionID'] ] = inspection
        inspection = singlelineToDict('1106432,LITTLE HARVARD ACADEMY,LITTLE HARVARD ACADEMY,2215573,Daycare (2 - 6 Years),Risk 1 (High),2708 W PETERSON AVE ,CHICAGO,IL,60659,03/08/2013,License,Fail,"29. PREVIOUS MINOR VIOLATION(S) CORRECTED 7-42-090 - Comments: PREVIOUS MINOR VIOLATIONS NOT CORRECTED FROM 4-23-12, REPORT #1214246 ')
        testCase[inspection['InspectionID'] ] = inspection
        inspection = singlelineToDict('1326209,SUPERMERCADO EL TAXQUENITO,SUPERMERCADO EL TAXQUENITO,2240202,Grocery Store,Risk 1 (High),6309 W GRAND AVE ,CHICAGO,IL,60639,03/08/2013,License,Fail,"35. WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTRUCTED PER CODE: GOOD REPAIR, SURFACES CLEAN AND DUST-LESS CLEANING METHODS - Comments: MUST REPLACE ALL STAINED CEILING TILE IN FRONT AREA OF STORE | 32. FOOD AND NON-FOOD CONTACT SURFACES PROPERLY DESIGNED, CONSTRUCTED AND MAINTAINED - Comments: MUST PROVIDE SPLASH GUARD AT BOTH EXPOSED HAND SINK AT PREP AREAS, AND SEAL RAW WOOD SHELVING AT PRODUCE AREA | 38. VENTILATION: ROOMS AND EQUIPMENT VENTED AS REQUIRED: PLUMBING: INSTALLED AND MAINTAINED - Comments: MUST PROVIDE A MOP SINK IN REAR STORAGE AREA AND REMOVE FROM COOKING PREP AREA | 11. ADEQUATE NUMBER, CONVENIENT, ACCESSIBLE, DESIGNED, AND MAINTAINED - Comments: MUST PROVIDE EXPOSED HAND SINK IN REAR COOKING PREP AREA, AND REMOVE MOP SINK TO ANOTHER LOCATION | 36. LIGHTING: REQUIRED MINIMUM FOOT-CANDLES OF LIGHT PROVIDED, FIXTURES SHIELDED - Comments: MUST PROVIDE LIGHT SHIELDS ON ALL LIGHTS REAR AREA, PROVIDE SHIELDED BULBS FOR HOT HOLDING UNIT, AND PROVIDE LIGHT IN REAR STORAGE AREA, LIGHT TOO DIM | 41. PREMISES MAINTAINED FREE OF LITTER, UNNECESSARY ARTICLES, CLEANING  EQUIPMENT PROPERLY STORED - Comments: MUST REMOVE ALL UNUSED EQUIPMENT FROM PREMISES",41.92189422993173,-87.78339752005009,"(41.92189422993173, -87.78339752005009)"')
        testCase[inspection['InspectionID'] ] = inspection
        inspection = singlelineToDict('1106431,FIRST  ACADEMY,FIRST  ACADEMY,2215961,Daycare (2 - 6 Years),Risk 1 (High),2459 W PETERSON AVE ,CHICAGO,IL,60659,03/08/2013,License,Fail,"18. NO EVIDENCE OF RODENT OR INSECT OUTER OPENINGS PROTECTED/RODENT PROOFED, A WRITTEN LOG SHALL BE MAINTAINED AVAILABLE TO THE INSPECTORS - Comments: WE(CERTIFIED FOOD HANDLER AND MYSELF)OBSERVED 12 LIVE GNATS ON WALLS AND FLOOR DRAIN IN THE KITCHEN. INSTRUCTED TO REMOVE GNATS ,WASH AND SANITIZE AREA. SERIOUS VIOLATION: 7-38-020 | 38. VENTILATION: ROOMS AND EQUIPMENT VENTED AS REQUIRED: PLUMBING: INSTALLED AND MAINTAINED - Comments: PROVIDE HOT WATER AT WASH BOWL INSIDE THE  SOUTH WASHROOM IN BASEMENT. PREMISES HAS PLENTY (5) WASHROOMS AND WASH BOWLS THROUGHOUT THE PREMISES. | 34. FLOORS: CONSTRUCTED PER CODE, CLEANED, GOOD REPAIR, COVERING INSTALLED, DUST-LESS CLEANING METHODS USED - Comments: SWEEP FLOOR IN FURNACE AREA,ELEVATE 6\' OFF THE FLOOR. REPLACE BROKEN FLOOR NORTH-WEST CORNER INSIDE  THE FURNACE AREA  | 37. TOILET ROOM DOORS SELF CLOSING: DRESSING ROOMS WITH LOCKERS PROVIDED: COMPLETE SEPARATION FROM LIVING/SLEEPING QUARTERS - Comments: A SELF CLOSING DEVICE IS NEEDED AT STAFF WASHROOM, IN KITCHEN .",41.99037475033571,-87.69203687906483,"(41.99037475033571, -87.69203687906483)"')
        testCase[inspection['InspectionID'] ] = inspection
        inspection = singlelineToDict('1322204,UNITED GRILL,UNITED GRILL,1337580,Restaurant,Risk 1 (High),4803 W ARMITAGE AVE ,CHICAGO,IL,60639,03/08/2013,Canvass Re-Inspection,Pass,"32. FOOD AND NON-FOOD CONTACT SURFACES PROPERLY DESIGNED, CONSTRUCTED AND MAINTAINED - Comments:  MUST REPLACE/RESEAL RUSTY WIRE SHELVING IN REAR REACH-IN COOLER AND MUST PROVIDE SPLASH GUARD AT EXPOSED HAND SINK IN REAR KITCHEN AREA ')
        testCase[inspection['InspectionID'] ] = inspection
        inspection = singlelineToDict('1084431,LA CATRINA CAFE,LA CATRINA CAFE,2185072,Restaurant,Risk 2 (Medium),1011 W 18TH ST ,CHICAGO,IL,60618,03/08/2013,License,Pass,"32. FOOD AND NON-FOOD CONTACT SURFACES PROPERLY DESIGNED, CONSTRUCTED AND MAINTAINED - Comments: THE THREE COMPARTMENT SINK BACKSPLASH IS RAW WOOD, SEAL ALL RAW WOOD SO IT IS EASY TO CLEAN.",41.85790269277439,-87.65215620861207,"(41.85790269277439, -87.65215620861207)"')
        testCase[inspection['InspectionID'] ] = inspection
        inspection = singlelineToDict('1322202,CAFETERIA MARIANAO 2,CAFETERIA MARIANAO 2,1382716,Restaurant,Risk 1 (High),4825 W ARMITAGE AVE ,CHICAGO,IL,60639,03/08/2013,Canvass Re-Inspection,Pass,"18. NO EVIDENCE OF RODENT OR INSECT OUTER OPENINGS PROTECTED/RODENT PROOFED, A WRITTEN LOG SHALL BE MAINTAINED AVAILABLE TO THE INSPECTORS - Comments: DOOR NOW IN GOOD REPAIR, AND NOTICED NO FRY ACTIVITY AT THIS TIME OF INSPECTION, VIOLATION NOW CORRECTED AND ABATED | 36. LIGHTING: REQUIRED MINIMUM FOOT-CANDLES OF LIGHT PROVIDED, FIXTURES SHIELDED - Comments: VIOLATION NOW CORRECTED AND ABATED | 37. TOILET ROOM DOORS SELF CLOSING: DRESSING ROOMS WITH LOCKERS PROVIDED: COMPLETE SEPARATION FROM LIVING/SLEEPING QUARTERS - Comments: VIOLATION NOW CORRECTED AND ABATED | 40. REFRIGERATION AND METAL STEM THERMOMETERS PROVIDED AND CONSPICUOUS - Comments: VIOLATION NOW CORRECTED AND ABATED | 35. WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTRUCTED PER CODE: GOOD REPAIR, SURFACES CLEAN AND DUST-LESS CLEANING METHODS - Comments: THE CEILING IN BSMT PREP AREA NOT CONSTRUCTED PROPERLY OPEN HOLE, WALL IN BASEMENT HAS OPEN HOLE BY PREP AREA, | 38. VENTILATION: ROOMS AND EQUIPMENT VENTED AS REQUIRED: PLUMBING: INSTALLED AND MAINTAINED - Comments: BACK FLOW PREVENTER IS NEEDED AT THE COFFEE EXPRESS MACHINE, ')
        testCase[inspection['InspectionID'] ] = inspection
        self.assertTrue( not inspectionResults(testCase))
        
    def test_restaurantsTypes(self):
        testCase = dict()
        testCase["control chart title"] = 'FacilityTypeTest.htm'
        testCase["control chart options"] = """
        var options = {
          title: 'Facility Type',
          is3D: true,
        };
        """
        inspection = singlelineToDict('1326219,EUREST DINING,CAFE 330,2233306,Restaurant,Risk 1 (High),330 N WABASH AVE ,CHICAGO,IL,60611,03/08/2013,License Re-Inspection,Pass,,,,')
        testCase[inspection['InspectionID'] ] = inspection
        inspection = singlelineToDict('1326216,INSOMNIA COOKIES,,2231962,,,2260 N LINCOLN AVE ,CHICAGO,IL,60614,03/08/2013,License,Fail,,41.92316234375516,-87.64578239312512,"(41.92316234375516, -87.64578239312512)"')
        testCase[inspection['InspectionID'] ] = inspection
        inspection = singlelineToDict('1326213,GALE STREET INN,GALE STREET INN,39301,Restaurant,Risk 1 (High),4914 N MILWAUKEE AVE ,CHICAGO,IL,60630,03/08/2013,Complaint,Pass,"40. REFRIGERATION AND METAL STEM THERMOMETERS PROVIDED AND CONSPICUOUS - Comments: INSTRUCTED TO PROVIDE THERMOMETER VISIBLE INSIDE (2) WALK-IN COOLER. | 41. PREMISES MAINTAINED FREE OF LITTER, UNNECESSARY ARTICLES, CLEANING  EQUIPMENT PROPERLY STORED - Comments: INSTRUCTED TO REMOVE UNNECESSARY ARTICLES STORED ON TOP OF WALK-IN COOLER AND WALK-IN FREEZER TO PREVENT PEST HARBORAGE. | 38. VENTILATION: ROOMS AND EQUIPMENT VENTED AS REQUIRED: PLUMBING: INSTALLED AND MAINTAINED - Comments: INSTRUCTED TO FIX LEAKY (COLD) FAUCET HANDLE LEAK AT EXPOSED HANDSINK IN MAIN PREP AREA (COOKING LINE).",41.97001167825235,-87.76279618588528,"(41.97001167825235, -87.76279618588528)"')
        testCase[inspection['InspectionID'] ] = inspection
        inspection = singlelineToDict('1326212,WILLIAM\'S PRODUCE,WILLIAM\'S PRODUCE,2079521,GROCERY STORE/TAQUERIA,Risk 1 (High),6309 W GRAND AVE ,CHICAGO,IL,60639,03/08/2013,Canvass,Out of Business,,41.92189422993173,-87.78339752005009,"(41.92189422993173, -87.78339752005009)"')
        testCase[inspection['InspectionID'] ] = inspection
        inspection = singlelineToDict('1106432,LITTLE HARVARD ACADEMY,LITTLE HARVARD ACADEMY,2215573,Daycare (2 - 6 Years),Risk 1 (High),2708 W PETERSON AVE ,CHICAGO,IL,60659,03/08/2013,License,Fail,"29. PREVIOUS MINOR VIOLATION(S) CORRECTED 7-42-090 - Comments: PREVIOUS MINOR VIOLATIONS NOT CORRECTED FROM 4-23-12, REPORT #1214246 ')
        testCase[inspection['InspectionID'] ] = inspection
        inspection = singlelineToDict('1326209,SUPERMERCADO EL TAXQUENITO,SUPERMERCADO EL TAXQUENITO,2240202,Grocery Store,Risk 1 (High),6309 W GRAND AVE ,CHICAGO,IL,60639,03/08/2013,License,Fail,"35. WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTRUCTED PER CODE: GOOD REPAIR, SURFACES CLEAN AND DUST-LESS CLEANING METHODS - Comments: MUST REPLACE ALL STAINED CEILING TILE IN FRONT AREA OF STORE | 32. FOOD AND NON-FOOD CONTACT SURFACES PROPERLY DESIGNED, CONSTRUCTED AND MAINTAINED - Comments: MUST PROVIDE SPLASH GUARD AT BOTH EXPOSED HAND SINK AT PREP AREAS, AND SEAL RAW WOOD SHELVING AT PRODUCE AREA | 38. VENTILATION: ROOMS AND EQUIPMENT VENTED AS REQUIRED: PLUMBING: INSTALLED AND MAINTAINED - Comments: MUST PROVIDE A MOP SINK IN REAR STORAGE AREA AND REMOVE FROM COOKING PREP AREA | 11. ADEQUATE NUMBER, CONVENIENT, ACCESSIBLE, DESIGNED, AND MAINTAINED - Comments: MUST PROVIDE EXPOSED HAND SINK IN REAR COOKING PREP AREA, AND REMOVE MOP SINK TO ANOTHER LOCATION | 36. LIGHTING: REQUIRED MINIMUM FOOT-CANDLES OF LIGHT PROVIDED, FIXTURES SHIELDED - Comments: MUST PROVIDE LIGHT SHIELDS ON ALL LIGHTS REAR AREA, PROVIDE SHIELDED BULBS FOR HOT HOLDING UNIT, AND PROVIDE LIGHT IN REAR STORAGE AREA, LIGHT TOO DIM | 41. PREMISES MAINTAINED FREE OF LITTER, UNNECESSARY ARTICLES, CLEANING  EQUIPMENT PROPERLY STORED - Comments: MUST REMOVE ALL UNUSED EQUIPMENT FROM PREMISES",41.92189422993173,-87.78339752005009,"(41.92189422993173, -87.78339752005009)"')
        testCase[inspection['InspectionID'] ] = inspection
        inspection = singlelineToDict('1106431,FIRST  ACADEMY,FIRST  ACADEMY,2215961,Daycare (2 - 6 Years),Risk 1 (High),2459 W PETERSON AVE ,CHICAGO,IL,60659,03/08/2013,License,Fail,"18. NO EVIDENCE OF RODENT OR INSECT OUTER OPENINGS PROTECTED/RODENT PROOFED, A WRITTEN LOG SHALL BE MAINTAINED AVAILABLE TO THE INSPECTORS - Comments: WE(CERTIFIED FOOD HANDLER AND MYSELF)OBSERVED 12 LIVE GNATS ON WALLS AND FLOOR DRAIN IN THE KITCHEN. INSTRUCTED TO REMOVE GNATS ,WASH AND SANITIZE AREA. SERIOUS VIOLATION: 7-38-020 | 38. VENTILATION: ROOMS AND EQUIPMENT VENTED AS REQUIRED: PLUMBING: INSTALLED AND MAINTAINED - Comments: PROVIDE HOT WATER AT WASH BOWL INSIDE THE  SOUTH WASHROOM IN BASEMENT. PREMISES HAS PLENTY (5) WASHROOMS AND WASH BOWLS THROUGHOUT THE PREMISES. | 34. FLOORS: CONSTRUCTED PER CODE, CLEANED, GOOD REPAIR, COVERING INSTALLED, DUST-LESS CLEANING METHODS USED - Comments: SWEEP FLOOR IN FURNACE AREA,ELEVATE 6\' OFF THE FLOOR. REPLACE BROKEN FLOOR NORTH-WEST CORNER INSIDE  THE FURNACE AREA  | 37. TOILET ROOM DOORS SELF CLOSING: DRESSING ROOMS WITH LOCKERS PROVIDED: COMPLETE SEPARATION FROM LIVING/SLEEPING QUARTERS - Comments: A SELF CLOSING DEVICE IS NEEDED AT STAFF WASHROOM, IN KITCHEN .",41.99037475033571,-87.69203687906483,"(41.99037475033571, -87.69203687906483)"')
        testCase[inspection['InspectionID'] ] = inspection
        inspection = singlelineToDict('1322204,UNITED GRILL,UNITED GRILL,1337580,Restaurant,Risk 1 (High),4803 W ARMITAGE AVE ,CHICAGO,IL,60639,03/08/2013,Canvass Re-Inspection,Pass,"32. FOOD AND NON-FOOD CONTACT SURFACES PROPERLY DESIGNED, CONSTRUCTED AND MAINTAINED - Comments:  MUST REPLACE/RESEAL RUSTY WIRE SHELVING IN REAR REACH-IN COOLER AND MUST PROVIDE SPLASH GUARD AT EXPOSED HAND SINK IN REAR KITCHEN AREA ')
        testCase[inspection['InspectionID'] ] = inspection
        inspection = singlelineToDict('1084431,LA CATRINA CAFE,LA CATRINA CAFE,2185072,Restaurant,Risk 2 (Medium),1011 W 18TH ST ,CHICAGO,IL,60618,03/08/2013,License,Pass,"32. FOOD AND NON-FOOD CONTACT SURFACES PROPERLY DESIGNED, CONSTRUCTED AND MAINTAINED - Comments: THE THREE COMPARTMENT SINK BACKSPLASH IS RAW WOOD, SEAL ALL RAW WOOD SO IT IS EASY TO CLEAN.",41.85790269277439,-87.65215620861207,"(41.85790269277439, -87.65215620861207)"')
        testCase[inspection['InspectionID'] ] = inspection
        inspection = singlelineToDict('1322202,CAFETERIA MARIANAO 2,CAFETERIA MARIANAO 2,1382716,Restaurant,Risk 1 (High),4825 W ARMITAGE AVE ,CHICAGO,IL,60639,03/08/2013,Canvass Re-Inspection,Pass,"18. NO EVIDENCE OF RODENT OR INSECT OUTER OPENINGS PROTECTED/RODENT PROOFED, A WRITTEN LOG SHALL BE MAINTAINED AVAILABLE TO THE INSPECTORS - Comments: DOOR NOW IN GOOD REPAIR, AND NOTICED NO FRY ACTIVITY AT THIS TIME OF INSPECTION, VIOLATION NOW CORRECTED AND ABATED | 36. LIGHTING: REQUIRED MINIMUM FOOT-CANDLES OF LIGHT PROVIDED, FIXTURES SHIELDED - Comments: VIOLATION NOW CORRECTED AND ABATED | 37. TOILET ROOM DOORS SELF CLOSING: DRESSING ROOMS WITH LOCKERS PROVIDED: COMPLETE SEPARATION FROM LIVING/SLEEPING QUARTERS - Comments: VIOLATION NOW CORRECTED AND ABATED | 40. REFRIGERATION AND METAL STEM THERMOMETERS PROVIDED AND CONSPICUOUS - Comments: VIOLATION NOW CORRECTED AND ABATED | 35. WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTRUCTED PER CODE: GOOD REPAIR, SURFACES CLEAN AND DUST-LESS CLEANING METHODS - Comments: THE CEILING IN BSMT PREP AREA NOT CONSTRUCTED PROPERLY OPEN HOLE, WALL IN BASEMENT HAS OPEN HOLE BY PREP AREA, | 38. VENTILATION: ROOMS AND EQUIPMENT VENTED AS REQUIRED: PLUMBING: INSTALLED AND MAINTAINED - Comments: BACK FLOW PREVENTER IS NEEDED AT THE COFFEE EXPRESS MACHINE, ')
        testCase[inspection['InspectionID'] ] = inspection
        self.assertTrue( not restaurantsTypes(testCase))
if __name__ == '__main__':
    unittest.main()