import unittest
from fooddata import relativeRisk, singlelineToDict
# import fuctions for testing
#import testFunction from testFile # replace with the name of your file and fuctions
#to test simply run 'python boilerplatetester.py'

class oneFuntionTester(unittest.TestCase):
    def test_relativeRisk(self):
        """Does the test case return true when expected"""
        expectedResult = False #expected result for good data
        testCase = dict()
        testCase["control open chart"] = True
        testCase["control chart title"] = 'inspectionResultsTest.htm'
        testCase["control chart options"] = """
        var options = {
          title: 'Inspection Results',
          is3D: true,
        };
        """
        inspection = singlelineToDict('1326219,EUREST DINING,CAFE 330,2233306,Restaurant,Risk 1 (High),330 N WABASH AVE ,CHICAGO,IL,60611,03/08/2013,License Re-Inspection,Pass,,,,')
        testCase[inspection['InspectionID'] ] = inspection
        inspection = singlelineToDict('1326216,INSOMNIA COOKIES,,2231962,,,2260 N LINCOLN AVE ,CHICAGO,IL,60614,03/08/2013,License,Fail,,41.92316234375516,-87.64578239312512,"(41.92316234375516, -87.64578239312512)"')
        testCase[inspection['InspectionID'] ] = inspection
        inspection = singlelineToDict('1326213,GALE STREET INN,GALE STREET INN,39301,Restaurant,Risk 1 (High),4914 N MILWAUKEE AVE ,CHICAGO,IL,60630,03/08/2013,Complaint,Pass,"40. REFRIGERATION AND METAL STEM THERMOMETERS PROVIDED AND CONSPICUOUS - Comments: INSTRUCTED TO PROVIDE THERMOMETER VISIBLE INSIDE (2) WALK-IN COOLER. | 41. PREMISES MAINTAINED FREE OF LITTER, UNNECESSARY ARTICLES, CLEANING  EQUIPMENT PROPERLY STORED - Comments: INSTRUCTED TO REMOVE UNNECESSARY ARTICLES STORED ON TOP OF WALK-IN COOLER AND WALK-IN FREEZER TO PREVENT PEST HARBORAGE. | 38. VENTILATION: ROOMS AND EQUIPMENT VENTED AS REQUIRED: PLUMBING: INSTALLED AND MAINTAINED - Comments: INSTRUCTED TO FIX LEAKY (COLD) FAUCET HANDLE LEAK AT EXPOSED HANDSINK IN MAIN PREP AREA (COOKING LINE).",41.97001167825235,-87.76279618588528,"(41.97001167825235, -87.76279618588528)"')
        testCase[inspection['InspectionID'] ] = inspection
        inspection = singlelineToDict('1326212,WILLIAM\'S PRODUCE,WILLIAM\'S PRODUCE,2079521,GROCERY STORE/TAQUERIA,Risk 1 (High),6309 W GRAND AVE ,CHICAGO,IL,60639,03/08/2013,Canvass,Out of Business,,41.92189422993173,-87.78339752005009,"(41.92189422993173, -87.78339752005009)"')
        testCase[inspection['InspectionID'] ] = inspection
        inspection = singlelineToDict('1106432,LITTLE HARVARD ACADEMY,LITTLE HARVARD ACADEMY,2215573,Daycare (2 - 6 Years),Risk 1 (High),2708 W PETERSON AVE ,CHICAGO,IL,60659,03/08/2013,License,Fail,"29. PREVIOUS MINOR VIOLATION(S) CORRECTED 7-42-090 - Comments: PREVIOUS MINOR VIOLATIONS NOT CORRECTED FROM 4-23-12, REPORT #1214246 ')
        testCase[inspection['InspectionID'] ] = inspection
        inspection = singlelineToDict('1326209,SUPERMERCADO EL TAXQUENITO,SUPERMERCADO EL TAXQUENITO,2240202,Grocery Store,Risk 1 (High),6309 W GRAND AVE ,CHICAGO,IL,60639,03/08/2013,License,Fail,"35. WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTRUCTED PER CODE: GOOD REPAIR, SURFACES CLEAN AND DUST-LESS CLEANING METHODS - Comments: MUST REPLACE ALL STAINED CEILING TILE IN FRONT AREA OF STORE | 32. FOOD AND NON-FOOD CONTACT SURFACES PROPERLY DESIGNED, CONSTRUCTED AND MAINTAINED - Comments: MUST PROVIDE SPLASH GUARD AT BOTH EXPOSED HAND SINK AT PREP AREAS, AND SEAL RAW WOOD SHELVING AT PRODUCE AREA | 38. VENTILATION: ROOMS AND EQUIPMENT VENTED AS REQUIRED: PLUMBING: INSTALLED AND MAINTAINED - Comments: MUST PROVIDE A MOP SINK IN REAR STORAGE AREA AND REMOVE FROM COOKING PREP AREA | 11. ADEQUATE NUMBER, CONVENIENT, ACCESSIBLE, DESIGNED, AND MAINTAINED - Comments: MUST PROVIDE EXPOSED HAND SINK IN REAR COOKING PREP AREA, AND REMOVE MOP SINK TO ANOTHER LOCATION | 36. LIGHTING: REQUIRED MINIMUM FOOT-CANDLES OF LIGHT PROVIDED, FIXTURES SHIELDED - Comments: MUST PROVIDE LIGHT SHIELDS ON ALL LIGHTS REAR AREA, PROVIDE SHIELDED BULBS FOR HOT HOLDING UNIT, AND PROVIDE LIGHT IN REAR STORAGE AREA, LIGHT TOO DIM | 41. PREMISES MAINTAINED FREE OF LITTER, UNNECESSARY ARTICLES, CLEANING  EQUIPMENT PROPERLY STORED - Comments: MUST REMOVE ALL UNUSED EQUIPMENT FROM PREMISES",41.92189422993173,-87.78339752005009,"(41.92189422993173, -87.78339752005009)"')
        testCase[inspection['InspectionID'] ] = inspection
        inspection = singlelineToDict('1106431,FIRST  ACADEMY,FIRST  ACADEMY,2215961,Daycare (2 - 6 Years),Risk 1 (High),2459 W PETERSON AVE ,CHICAGO,IL,60659,03/08/2013,License,Fail,"18. NO EVIDENCE OF RODENT OR INSECT OUTER OPENINGS PROTECTED/RODENT PROOFED, A WRITTEN LOG SHALL BE MAINTAINED AVAILABLE TO THE INSPECTORS - Comments: WE(CERTIFIED FOOD HANDLER AND MYSELF)OBSERVED 12 LIVE GNATS ON WALLS AND FLOOR DRAIN IN THE KITCHEN. INSTRUCTED TO REMOVE GNATS ,WASH AND SANITIZE AREA. SERIOUS VIOLATION: 7-38-020 | 38. VENTILATION: ROOMS AND EQUIPMENT VENTED AS REQUIRED: PLUMBING: INSTALLED AND MAINTAINED - Comments: PROVIDE HOT WATER AT WASH BOWL INSIDE THE  SOUTH WASHROOM IN BASEMENT. PREMISES HAS PLENTY (5) WASHROOMS AND WASH BOWLS THROUGHOUT THE PREMISES. | 34. FLOORS: CONSTRUCTED PER CODE, CLEANED, GOOD REPAIR, COVERING INSTALLED, DUST-LESS CLEANING METHODS USED - Comments: SWEEP FLOOR IN FURNACE AREA,ELEVATE 6\' OFF THE FLOOR. REPLACE BROKEN FLOOR NORTH-WEST CORNER INSIDE  THE FURNACE AREA  | 37. TOILET ROOM DOORS SELF CLOSING: DRESSING ROOMS WITH LOCKERS PROVIDED: COMPLETE SEPARATION FROM LIVING/SLEEPING QUARTERS - Comments: A SELF CLOSING DEVICE IS NEEDED AT STAFF WASHROOM, IN KITCHEN .",41.99037475033571,-87.69203687906483,"(41.99037475033571, -87.69203687906483)"')
        testCase[inspection['InspectionID'] ] = inspection
        inspection = singlelineToDict('1322204,UNITED GRILL,UNITED GRILL,1337580,Restaurant,Risk 1 (High),4803 W ARMITAGE AVE ,CHICAGO,IL,60639,03/08/2013,Canvass Re-Inspection,Pass,"32. FOOD AND NON-FOOD CONTACT SURFACES PROPERLY DESIGNED, CONSTRUCTED AND MAINTAINED - Comments:  MUST REPLACE/RESEAL RUSTY WIRE SHELVING IN REAR REACH-IN COOLER AND MUST PROVIDE SPLASH GUARD AT EXPOSED HAND SINK IN REAR KITCHEN AREA ')
        testCase[inspection['InspectionID'] ] = inspection
        inspection = singlelineToDict('1084431,LA CATRINA CAFE,LA CATRINA CAFE,2185072,Restaurant,Risk 2 (Medium),1011 W 18TH ST ,CHICAGO,IL,60618,03/08/2013,License,Pass,"32. FOOD AND NON-FOOD CONTACT SURFACES PROPERLY DESIGNED, CONSTRUCTED AND MAINTAINED - Comments: THE THREE COMPARTMENT SINK BACKSPLASH IS RAW WOOD, SEAL ALL RAW WOOD SO IT IS EASY TO CLEAN.",41.85790269277439,-87.65215620861207,"(41.85790269277439, -87.65215620861207)"')
        testCase[inspection['InspectionID'] ] = inspection
        inspection = singlelineToDict('1322202,CAFETERIA MARIANAO 2,CAFETERIA MARIANAO 2,1382716,Restaurant,Risk 1 (High),4825 W ARMITAGE AVE ,CHICAGO,IL,60639,03/08/2013,Canvass Re-Inspection,Pass,"18. NO EVIDENCE OF RODENT OR INSECT OUTER OPENINGS PROTECTED/RODENT PROOFED, A WRITTEN LOG SHALL BE MAINTAINED AVAILABLE TO THE INSPECTORS - Comments: DOOR NOW IN GOOD REPAIR, AND NOTICED NO FRY ACTIVITY AT THIS TIME OF INSPECTION, VIOLATION NOW CORRECTED AND ABATED | 36. LIGHTING: REQUIRED MINIMUM FOOT-CANDLES OF LIGHT PROVIDED, FIXTURES SHIELDED - Comments: VIOLATION NOW CORRECTED AND ABATED | 37. TOILET ROOM DOORS SELF CLOSING: DRESSING ROOMS WITH LOCKERS PROVIDED: COMPLETE SEPARATION FROM LIVING/SLEEPING QUARTERS - Comments: VIOLATION NOW CORRECTED AND ABATED | 40. REFRIGERATION AND METAL STEM THERMOMETERS PROVIDED AND CONSPICUOUS - Comments: VIOLATION NOW CORRECTED AND ABATED | 35. WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTRUCTED PER CODE: GOOD REPAIR, SURFACES CLEAN AND DUST-LESS CLEANING METHODS - Comments: THE CEILING IN BSMT PREP AREA NOT CONSTRUCTED PROPERLY OPEN HOLE, WALL IN BASEMENT HAS OPEN HOLE BY PREP AREA, | 38. VENTILATION: ROOMS AND EQUIPMENT VENTED AS REQUIRED: PLUMBING: INSTALLED AND MAINTAINED - Comments: BACK FLOW PREVENTER IS NEEDED AT THE COFFEE EXPRESS MACHINE, ')
        testCase[inspection['InspectionID'] ] = inspection
        self.assertTrue(not relativeRisk(testCase))
    
if __name__ == '__main__':
    unittest.main()